openapi: 3.0.2
info:
    title: Bank
    version: 1.0.0
    description: Maarek Sillamäe Karel Kivimägi bank
    contact:
        name: Maarek Sillamäe karel kivimägi
        email: maarek.sillamae@khk.ee
paths:
    /api/user/register:
        description: ''
        post:
            requestBody:
                description: User created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postUsersRequest'
                required: true
            servers:
                -
                    url: 'http://localhost:1337'
                    description: Development server
            tags:
                - User
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postUsersRequest'
                            examples:
                                userCreated:
                                    value:
                                        message: User saved
                    description: User saved
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                userAlreadyExists:
                                    value: '{error: "All fields must be filled"}'
                                passwordLenght:
                                    value:
                                        error: Password length must be 8 or more characters
                    description: All fields must be filled
                '409':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                usernameAlreadyExists:
                                    value: '{error: "Username already exists"}'
                    description: Username already exists
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                oopsSomethingWentWrong:
                                    value:
                                        error: Oops! Something went wrong
                    description: Oops! Something went wrong
            summary: Register a new user
            description: Register a new user
    /api/session/create-session:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postSessionRequest'
                required: true
            tags:
                - Session
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionResponse'
                            examples:
                                tokenHasBeenCreated:
                                    value:
                                        token: 5f9db108b8c28c40a42d94c4
                    description: ''
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionResponse'
                            examples:
                                userAndPwRequired:
                                    value:
                                        error: Username and password required
                                invalidUsernameOrPassword:
                                    value:
                                        error: Invalid username or password
                    description: Invalid username or password
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionResponse'
                            examples:
                                oopsSomethingWentWrong:
                                    value:
                                        error: Oops! Something went wrong
                    description: Oops! Something went wrong
            description: Create session token
    /api/session/delete-session:
        delete:
            tags:
                - Session
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionResponse'
                            examples:
                                deleteToken:
                                    value:
                                        message: Token successfully deleted
                    description: Deleted token
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                missingAuthorizationHeader:
                                    value:
                                        error: Missing Authorization header
                                invalidHeaderFormat:
                                    value:
                                        error: Invalid Authorization header format
                                invalidToken:
                                    value:
                                        error: Invalid token
                                invalidMongooseToken:
                                    value:
                                        error: Invalid token
                    description: Missing token
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                sessionNotFound:
                                    value:
                                        error: Session not found
                    description: Not found
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                oopsSomethingWentWrong:
                                    value:
                                        error: Oops! Something went wrong
                    description: Server error
            security:
                -
                    Bearer: []
            description: Delete session token
    /api/accounts/current-user-account:
        get:
            tags:
                - Account
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/successfulResponse'
                            examples:
                                successfulResponse:
                                    value:
                                        name: Maarek Sillamäe karel kivimägi
                                        username: Maarek
                                        account:
                                            -
                                                account_number: EE2650749058303131
                                                balance: 50
                                                currency: EUR
                    description: Account information
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                missingAuthorizationHeader:
                                    value:
                                        error: Missing Authorization header
                                invalidHeaderFormat:
                                    value:
                                        error: Invalid Authorization header format
                                invalidToken:
                                    value: "\t{\"error\":\"Invalid token\"}"
                                invalidMongooseToken:
                                    value:
                                        error: Invalid token
                    description: |
                        Missing token
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                accountNotFound:
                                    value:
                                        error: Account not found
                                userNotFound:
                                    value:
                                        error: User not found
                    description: Not found
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                oopsSomethingWentWrong:
                                    value:
                                        error: Oops! Something went wrong
                    description: Server error
            security:
                -
                    Bearer: []
    /api/transactions/create-transactions:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postTransactionRequest'
                        examples:
                            createTransaction:
                                value:
                                    accountFrom: 7da3851546037313642
                                    accountTo: 7da3851546037313641
                                    explanation: raha
                                    amount: 50
                required: true
            tags:
                - Transactions
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/successfulTransaction'
                            examples:
                                transactionSuccessful:
                                    value:
                                        message: Transaction created successfully
                    description: Transaction created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                invalidAmount:
                                    value:
                                        error: Invalid amount
                                invalidAccountTo:
                                    value:
                                        error: Invalid accountTo
                    description: Invalid amount
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                missingAuthorizationHeader:
                                    value:
                                        error: Missing Authorization header
                    description: Missing token
                '402':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                insufficentFunds:
                                    value:
                                        error: Insufficient funds
                    description: Insufficent funds
            security:
                -
                    Bearer: []
            description: Transactions API
    /api/transactions/b2b:
        post:
            tags:
                - Transactions
            responses:
                '200':
                    description: Succesfully received transaction
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                parsingJwtFailed:
                                    value:
                                        error: Parsing JWT payload failed
                                verifyAccountTo:
                                    value:
                                        error: Account not found
                                bankNotFound:
                                    value:
                                        error: >-
                                            The account sending the funds does not belong to a bank registered
                                            in Central Bank
                                cannotVerifyJwksSignature:
                                    value:
                                        error: 'Cannot verify your signature: The jwksUrl of your bank is invalid'
                                invalidSignature:
                                    value:
                                        error: Invalid signature
                    description: Returns the errors specified
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                centralBankError:
                                    value:
                                        error: Central Bank error
                                missingJwksUrl:
                                    value:
                                        error: 'Cannot verify your signature: The jwksUrl of your bank is missing'
                    description: Returns the errors specified
    /api/transactions/jwks:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/keys'
                            examples:
                                keys:
                                    value:
                                        keys:
                                            -
                                                kty: RSA
                                                kid: h_s_zbvPAS1WB-ref6FF1_TIHANcpjPhV_xEk9WR6X4
                                                'n': >-
                                                    jdcp_0ewRa-dKQuqzSQD6nNsP8G-bfHcgl7fBshGCgznFYmGTiV2OuRQ1yIogdlfSBiQrol1P-IlfN1m5NKsR3iLw-PDOKFzoLf1fTQpuEZUsm5Ip-LpYgjCjjw8oOP7ZFqlkuR3XMj1rZYKiyhoRITxUZlz0v1LO1Wa736lO1E
                                                e: AQAB
                    description: Keys
components:
    schemas:
        postUsersRequest:
            description: ''
            required:
                - name
                - password
                - username
            type: object
            properties:
                name:
                    description: Full name
                    type: string
                password:
                    description: Minimum 8 characters
                    type: string
                username:
                    description: ''
                    type: string
            example:
                name: some text
                password: some text
                username: some text
        errorResponse:
            title: Error response
            description: Generic error response
            required:
                - missingAuthorizationHeader
                - error
                - invalidHeaderFormat
                - invalidToken
                - invalidMongooseToken
                - insufficentFunds
                - invalidAmount
                - invalidAccountTo
                - cannotTransferToYourself
            type: object
            properties:
                error:
                    description: Error response
                    type: string
                missingAuthorizationHeader:
                    description: '{"error":"Missing Authorization header"}'
                    type: string
                invalidHeaderFormat:
                    description: "\t{\"error\":\"Invalid Authorization header format\"}"
                    type: string
                invalidToken:
                    description: '{"error":"Invalid token"}'
                    type: string
                invalidMongooseToken:
                    description: '{"error":"Invalid token"}'
                    type: string
                insufficentFunds:
                    description: '{ "error": ''Insufficient funds'' }'
                    type: string
                invalidAmount:
                    description: '{ "error": ''Invalid amount'' }'
                    type: string
                invalidAccountTo:
                    description: '{ "error": ''Invalid accountTo'' }'
                    type: string
                cannotTransferToYourself:
                    description: '{"error": "You cannot transfer to yourself"}'
                    type: string
            example:
                error: Error message
        postSessionResponse:
            description: ''
            type: object
            example:
                token: 5f9db108b8c28c40a42d94c4
        postSessionRequest:
            description: ''
            required:
                - username
                - password
            type: object
            properties:
                username:
                    description: ''
                    type: string
                password:
                    description: ''
                    type: string
            example:
                username: some text
                password: some text
        deleteSessionRequest:
            description: ''
            type: object
            example: {}
        deleteSessionResponse:
            description: ''
            type: object
            example:
                message: Token successfully deleted
        successfulResponse:
            description: ''
            required:
                - successful
            type: object
            properties:
                successful:
                    description: Successful response
                    type: string
            example:
                name: Maarek sillamäe karel kivimägi
                username: Maarek
                account:
                    -
                        account_number: EE2650749058303131
                        balance: 50
                        currency: EUR
        postTransactionRequest:
            description: ''
            required:
                - accountTo
                - amount
                - explanation
                - accountFrom
            type: object
            properties:
                accountTo:
                    description: Reciever
                    type: string
                explanation:
                    description: Transaction explanation
                    type: string
                amount:
                    description: Fund amount
                    type: integer
                accountFrom:
                    description: Sender
                    type: string
            example:
                accountFrom: 7da3851546037313642
                accountTo: 7da3851546037313641
                explanation: raha
                amount: 50
        successfulTransaction:
            title: Root Type for successfulTransaction
            description: ''
            type: object
            properties:
                message:
                    description: Success message
                    type: string
            example:
                message: Transaction created successfully
        parsingJwtFailed:
            description: ''
            type: object
            example:
                error: Parsing JWT payload failed
        verifyAccountTo:
            title: Root Type for verifyAccountTo
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Account not found
        bankNotFound:
            title: Root Type for bankNotFound
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: The account sending the funds does not belong to a bank registered in Central Bank
        cannotVerifyJwksSignature:
            title: Root Type for cannotVerifyJwksSignature
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: 'Cannot verify your signature: The jwksUrl of your bank is invalid'
        invalidSignature:
            title: Root Type for invalidSignature
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Invalid signature
        keys:
            title: Root Type for keys
            description: ''
            type: object
            properties:
                keys:
                    type: array
                    items:
                        type: object
                        properties:
                            kty:
                                type: string
                            kid:
                                type: string
                            'n':
                                type: string
                            e:
                                type: string
            example:
                keys:
                    -
                        kty: RSA
                        kid: h_s_zbvPAS1WB-ref6FF1_TIHANcpjPhV_xEk9WR6X4
                        'n': >-
                            jdcp_0ewRa-dKQuqzSQD6nNsP8G-bfHcgl7fBshGCgznFYmGTiV2OuRQ1yIogdlfSBiQrol1P-IlfN1m5NKsR3iLw-PDOKFzoLf1fTQpuEZUsm5Ip-LpYgjCjjw8oOP7ZFqlkuR3XMj1rZYKiyhoRITxUZlz0v1LO1Wa736lO1E
                        e: AQAB
    securitySchemes:
        Bearer:
            scheme: bearer
            type: http
